version: "3"
services:
  api:
    build:
      context: "."
      dockerfile: "./api/Dockerfile"
    ports:
      - 7000:7000
    volumes:
      - ./api:/opt/app

  client:
    build:
      context: "."
      dockerfile: "./client/Dockerfile"
    ports:
      - 7001:7001
    volumes:
      - ./client:/opt/app
